name: Build every hour

on:
  schedule:
    #    - cron: '0 * * * *'
    - cron: '*/5 * * * *'
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
      - name: curl
        uses: wei/curl@master
        with:
          args: "-X POST -H 'Authorization: token ${{ secrets.PAGES_ACCESS_TOKEN }}' -H 'Accept: application/vnd.github.ant-man-preview+json' https://api.github.com/repos/marwoj/marwoj.github.io/pages/builds"
