# Site
name: 'Re-connecting dots'
description: 'Mundana is a free Jekyll theme for awesome people like you, Medium like.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
disqus: 'demowebsite'
email: 'wowthemesnet@gmail.com'
#mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b' # Uncomment for subscriptions

include: [ "_pages" ]
permalink: /:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

authors:
  wojciech:
    name: Wojciech Marusarz
    avatar: assets/images/wojciech-marusarz.webp
    bio: >- # this means to ignore newlines until next property
      Lubię pracować w zespołach, gdzie jakość kodu i ukierunkowany rozwój projektu są kluczowe. W dłuższej
      perspektywie pozwala mi to na dogłębne zrozumienie tematu, rozwój osobisty i szukanie wyzwań. Zajmuje się
      programowaniem w Javie i Kotlinie. Dodatkowo interesuję się narzędziami Big Data oraz Data-Intensive.
    twitter: https://twitter.com/w_marusarz

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/wojciech-marusarz.webp

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [ README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules ]